//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mondo.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mondo.Globalization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hPA.
        /// </summary>
        internal static string AtmospericPressure_HectoPascals {
            get {
                return ResourceManager.GetString("AtmospericPressure_HectoPascals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inHg.
        /// </summary>
        internal static string AtmospericPressure_InchesMercury {
            get {
                return ResourceManager.GetString("AtmospericPressure_InchesMercury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cm.
        /// </summary>
        internal static string Distance_Centimeters {
            get {
                return ResourceManager.GetString("Distance_Centimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ft.
        /// </summary>
        internal static string Distance_Feet {
            get {
                return ResourceManager.GetString("Distance_Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        internal static string Distance_Inches {
            get {
                return ResourceManager.GetString("Distance_Inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        internal static string Distance_Kilometers {
            get {
                return ResourceManager.GetString("Distance_Kilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string Distance_Meters {
            get {
                return ResourceManager.GetString("Distance_Meters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mi.
        /// </summary>
        internal static string Distance_Miles {
            get {
                return ResourceManager.GetString("Distance_Miles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        internal static string Distance_Millimeters {
            get {
                return ResourceManager.GetString("Distance_Millimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yd.
        /// </summary>
        internal static string Distance_Yards {
            get {
                return ResourceManager.GetString("Distance_Yards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gal.
        /// </summary>
        internal static string Fluid_Gallons {
            get {
                return ResourceManager.GetString("Fluid_Gallons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        internal static string Fluid_Liters {
            get {
                return ResourceManager.GetString("Fluid_Liters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ml.
        /// </summary>
        internal static string Fluid_Milliliters {
            get {
                return ResourceManager.GetString("Fluid_Milliliters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oz.
        /// </summary>
        internal static string Fluid_Ounces {
            get {
                return ResourceManager.GetString("Fluid_Ounces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °C.
        /// </summary>
        internal static string Temperature_Celsius {
            get {
                return ResourceManager.GetString("Temperature_Celsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °F.
        /// </summary>
        internal static string Temperature_Fahrenheit {
            get {
                return ResourceManager.GetString("Temperature_Fahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °.
        /// </summary>
        internal static string Temperature_Symbol {
            get {
                return ResourceManager.GetString("Temperature_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KpH.
        /// </summary>
        internal static string Velocity_KPH {
            get {
                return ResourceManager.GetString("Velocity_KPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MpH.
        /// </summary>
        internal static string Velocity_MPH {
            get {
                return ResourceManager.GetString("Velocity_MPH", resourceCulture);
            }
        }
    }
}
